name: Build & Deploy WordPress N-tier Infra

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: wordpress-custom
  IMAGE_TAG: v1.0

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Container Registry Login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and push Docker image
        run: |
          ACR_LOGIN_SERVER=$(az acr show -n ${{ secrets.ACR_NAME }} --query loginServer -o tsv)
          docker build -t $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ./Docker
          docker push $ACR_LOGIN_SERVER/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  terraform-deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/envs/${{ secrets.TF_ENV }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        run: terraform init

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
        env:
          TF_VAR_mysql_administrator_password: ${{ secrets.TF_VAR_mysql_administrator_password }}
